name: build

on:
  workflow_call:
    inputs:
      push:
        description: "Push built image"
        default: true
        required: false
        type: boolean

defaults:
  run:
    shell: bash

jobs:
  setup:
    runs-on: ubuntu-slim
    timeout-minutes: 5
    outputs:
      names: ${{ steps.names.outputs.names }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - id: names
        run: echo "names=$(find . -maxdepth 1 -type f -name '*.dockerfile' -printf '%P\n' | sort | jq -cnR '[inputs | sub("\\.[^.]+?$"; "")]')" | tee "$GITHUB_OUTPUT"

  image:
    needs: setup
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        name: ${{ fromJSON(needs.setup.outputs.names) }}

    timeout-minutes: 15
    env:
      IMAGE: ghcr.io/${{ github.repository }}/${{ matrix.name }}
      IMAGE_NAME: ${{ matrix.name }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: docker_meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: ${{ env.IMAGE }}

      - id: docker_build
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          context: .
          file: ${{ matrix.name }}.dockerfile
          pull: true
          push: ${{ inputs.push }}
          outputs: type=docker,dest=${{ runner.temp }}/image.tar
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          annotations: ${{ steps.docker_meta.outputs.annotations }}
          provenance: false
          cache-from: |
            ${{ steps.docker_meta.outputs.tags }}
            ${{ env.IMAGE }}:${{ github.event.repository.default_branch }}
          cache-to: type=inline

      - id: podman_pull
        run: |
          imageid="$(podman pull "docker-archive:$RUNNER_TEMP/image.tar")"
          echo "imageid=$imageid" | head -n1 | tee "$GITHUB_OUTPUT"

      - id: gnome-session-wayland
        name: Test gnome-session-wayland
        run: test/test-wayland.sh "$IMAGE_ID"
        env:
          IMAGE_ID: ${{ steps.podman_pull.outputs.imageid }}

      - run: mv test/screenshot-wayland.png "test/$IMAGE_NAME-wayland.png"
        if: ${{ !cancelled() && steps.gnome-session-wayland.outcome != 'skipped' }}

      - name: Upload screenshot
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          path: test/${{ env.IMAGE_NAME }}-wayland.png
          archive: false
        if: ${{ !cancelled() && steps.gnome-session-wayland.outcome != 'skipped' }}

      - id: has-x11
        name: Check if X11 is available
        run: |
          cli_arg="$(podman run --rm "$IMAGE_ID" gnome-shell --help | grep -qF -- '--x11' && podman run --rm "$IMAGE_ID" sh -c 'command -V Xvfb >/dev/null' && echo 1 || echo 0)"
          echo "cli_arg=$cli_arg" | tee "$GITHUB_OUTPUT"
        env:
          IMAGE_ID: ${{ steps.podman_pull.outputs.imageid }}
        if: ${{ !cancelled() && steps.podman_pull.outcome == 'success' }}

      - id: gnome-session-x11
        name: Test gnome-session-x11
        run: test/test-x11.sh "$IMAGE_ID"
        if: ${{ !cancelled() && steps.has-x11.outcome == 'success' && fromJSON(steps.has-x11.outputs.cli_arg) }}
        env:
          IMAGE_ID: ${{ steps.podman_pull.outputs.imageid }}

      - run: mv test/screenshot-x11.png "test/$IMAGE_NAME-x11.png"
        if: ${{ !cancelled() && steps.gnome-session-x11.outcome != 'skipped' }}

      - name: Upload screenshot
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          path: test/${{ env.IMAGE_NAME }}-x11.png
          archive: false
        if: ${{ !cancelled() && steps.gnome-session-x11.outcome != 'skipped' }}
