name: cleanup

on:
  workflow_call:
    inputs:
      dry-run:
        description: "Don't delete images, just print messages"
        default: false
        required: false
        type: boolean

defaults:
  run:
    shell: bash

jobs:
  setup:
    runs-on: ubuntu-slim
    timeout-minutes: 5
    outputs:
      images: ${{ steps.images.outputs.names }}
      keep-tags: ${{ steps.keep-tags.outputs.tags }}

    env:
      GH_TOKEN: ${{ github.token }}
      GH_REPO: ${{ github.repository }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - id: images
        run: echo "names=$(find . -maxdepth 1 -type f -name '*.dockerfile' -printf '%P\n' | sort | jq -cnR '[inputs | sub("\\.[^.]+?$"; "")]')" | tee "$GITHUB_OUTPUT"

      - id: keep-tags
        run: >-
          {
            echo "tags<<*EOF*";
            {
              git for-each-ref --format='%(refname:strip=3)' refs/remotes;
              git for-each-ref --format='%(refname:strip=2)' refs/tags;
              gh pr list --template '{{range .}}pr-{{.number}}{{"\n"}}{{end}}' --json number;
            } | sed -E 's/[^a-zA-Z0-9._-]+/-/g';
            echo "*EOF*";
          } | tee "$GITHUB_OUTPUT"

  image:
    needs: setup
    runs-on: ubuntu-slim
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJSON(needs.setup.outputs.images) }}
        cache: [true]
        include:
          - image: alpine-3.19
            cache: false
          - image: ubuntu-25.04
            cache: false
          - image: fedora-41
            cache: false
          - image: fedora-42
            cache: false
          - image: opensuse-leap-15.6
            cache: false
          - image: alpine-3.20
            cache: false
          - image: ubuntu-25.10
            cache: false
          - image: alpine-3.21
            cache: false
          - image: alpine-3.22
            cache: false
          - image: alpine-3.23
            cache: false

    steps:
      - uses: amezin/container-registry-prune-action@4b4965427da5aa037005aa1849921efda619eaa9 # v0.4.5
        if: fromJSON(matrix.cache)
        with:
          name: ${{ github.event.repository.name }}/cache/${{ matrix.image }}
          tag-patterns: |
            ${{ github.event.repository.default_branch }}
            ${{ needs.setup.outputs.keep-tags }}
          matching-tags-retention-duration: 1m
          mismatching-tags-retention-duration: 1d
          untagged-retention-duration: 1d
          dry-run: ${{ inputs.dry-run }}

      - uses: amezin/container-registry-prune-action@4b4965427da5aa037005aa1849921efda619eaa9 # v0.4.5
        with:
          name: ${{ github.event.repository.name }}/${{ matrix.image }}
          tag-patterns: |
            latest
            +([0-9]).+([0-9]).+([0-9]).+([0-9])
            ${{ github.event.repository.default_branch }}
            ${{ needs.setup.outputs.keep-tags }}
          matching-tags-retention-duration: 1y
          mismatching-tags-retention-duration: 1d
          untagged-retention-duration: 1d
          dry-run: ${{ inputs.dry-run }}
