name: push
concurrency: ${{ github.workflow }}/${{ github.ref }}

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - master
    tags:
      - "*"

permissions:
  packages: write

jobs:
  ci:
    uses: ./.github/workflows/build.yml
