name: push
concurrency: ${{ github.workflow }}/${{ github.ref }}

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - master
    tags:
      - "*"

jobs:
  build:
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      packages: write

  release:
    uses: ./.github/workflows/release.yml
    with:
      dry-run: true
    permissions:
      contents: read
