name: release

on:
  workflow_call:
    inputs:
      dry-run:
        description: "Don't create release, just print messages"
        default: false
        required: false
        type: boolean

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-24.04
    env:
      GH_TOKEN: ${{ github.token }}
      GH_REPO: ${{ github.repository }}

    steps:
      - id: prefix
        run: echo "prefix=$(date --utc '+%Y.%m.%d.')" | tee "$GITHUB_OUTPUT"

      - id: existing-tags
        run: |
          EXISTING="$(gh api "/repos/{owner}/{repo}/git/matching-refs/tags/$PREFIX" | jq -c '[.[].ref]')"
          echo "refs=$EXISTING" | tee "$GITHUB_OUTPUT"

        env:
          PREFIX: ${{ steps.prefix.outputs.prefix }}

      - id: version
        run: |
          BUILD="$(echo "$EXISTING" | jq -c 'map(capture("\\.(?<n>[0-9]+)$") | .n | tonumber + 1) | . + [0] | max')"

          echo "build=$BUILD" | tee "$GITHUB_OUTPUT"
          echo "version=$PREFIX$BUILD" | tee "$GITHUB_OUTPUT"

        env:
          PREFIX: ${{ steps.prefix.outputs.prefix }}
          EXISTING: ${{ steps.existing-tags.outputs.refs }}

      - id: latest
        run: |
          LATEST="$(gh release list --limit 1 --json tagName -q '.[].tagName')"
          echo "latest=$LATEST" | tee "$GITHUB_OUTPUT"

      - id: should-release
        uses: amezin/compare-commit-files-action@dc331422131f743fcb2a4174ad5c74f719b69580 # v1.0.3
        with:
          files: |
            # Don't autorelease on CI changes. If necessary, a release can be created manually
            *.dockerfile
            .dockerignore
            data/**
            scripts/**
          base: ${{ steps.latest.outputs.latest }}

      - if: ${{ !inputs.dry-run && fromJSON(steps.should-release.outputs.changed) }}
        run: gh release create "$VERSION" --target "$GITHUB_SHA" --generate-notes --fail-on-no-commits --notes-start-tag "$LATEST"
        env:
          VERSION: ${{ steps.version.outputs.version }}
          LATEST: ${{ steps.latest.outputs.latest }}

      - if: ${{ !inputs.dry-run && fromJSON(steps.should-release.outputs.changed) }}
        run: gh workflow run push.yml --ref "refs/tags/$VERSION"
        env:
          VERSION: ${{ steps.version.outputs.version }}
